# Generated by Django 2.1 on 2018-08-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('total_events', models.IntegerField(default=0)),
                ('total_expenses', models.IntegerField(default=0)),
            ],
        ),
    ]
