# Generated by Django 2.1 on 2018-08-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeMoneyApp', '0002_auto_20180803_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Unnamed Event', max_length=256)),
                ('event_type', models.CharField(default='Unspecified Event Type', max_length=256)),
                ('event_start', models.DateTimeField(auto_now=True)),
                ('event_end', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
