# Generated by Django 2.1 on 2018-08-07 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TimeMoneyApp', '0005_auto_20180807_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeevent',
            name='event_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
